services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mevo
      POSTGRES_PASSWORD: mevo
      POSTGRES_DB: mevostats
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
